<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class MovimientosTableSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('movimientos')->insert([
            // ════════════════════════════════════════════════
            //  INGRESOS — Pagos recibidos de clientes
            // ════════════════════════════════════════════════

            // 1. Adelanto cliente 1 - Tramo 1 (Banco Unión BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2, // Banco Unión BOB
                'tipo'             => 'ingreso',
                'categoria'        => 'anticipo_cliente',
                'monto'            => 7000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 7000.00,
                'fecha'            => '2026-01-06',
                'concepto'         => 'Adelanto cliente 1 - Tramo Santa Cruz → La Paz (18.35 t)',
                'codigo_seguimiento'=> 'CLI-TRF-2026-001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCliente',
                'origen_id'        => 1,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 2. Pago final cliente 1 - Tramo 1 (QR → Banco Unión BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'ingreso',
                'categoria'        => 'pago_cliente',
                'monto'            => 7924.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 7924.00,
                'fecha'            => '2026-01-10',
                'concepto'         => 'Pago final cliente 1 - Tramo 1 entregado (14,924 BOB total)',
                'codigo_seguimiento'=> 'CLI-QR-2026-001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCliente',
                'origen_id'        => 2,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 3. Adelanto cliente 1 - Tramo 2 (Banco Unión BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'ingreso',
                'categoria'        => 'anticipo_cliente',
                'monto'            => 8000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 8000.00,
                'fecha'            => '2026-01-12',
                'concepto'         => 'Adelanto cliente 1 - Tramo Oruro → Cochabamba (21.8 t)',
                'codigo_seguimiento'=> 'CLI-TRF-2026-002',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCliente',
                'origen_id'        => 3,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 4. Adelanto cliente 2 - Tramo 4 internacional (Banco Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3, // Banco Bisa USD
                'tipo'             => 'ingreso',
                'categoria'        => 'anticipo_cliente',
                'monto'            => 1000.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 6960.00,
                'fecha'            => '2026-02-07',
                'concepto'         => 'Adelanto cliente 2 - Tramo Santa Cruz → São Paulo (19.9 t)',
                'codigo_seguimiento'=> 'CLI-USD-2026-001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCliente',
                'origen_id'        => 4,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 5. Pago parcial cliente 2 - Tramo 5 (Banco Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3,
                'tipo'             => 'ingreso',
                'categoria'        => 'pago_cliente',
                'monto'            => 1600.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 11136.00,
                'fecha'            => '2026-02-18',
                'concepto'         => 'Pago parcial cliente 2 - Tramo La Paz → Buenos Aires transbordado',
                'codigo_seguimiento'=> 'CLI-USD-2026-002',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCliente',
                'origen_id'        => 5,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 6. Adelanto cliente 3 - Tramo 6 (Caja Principal BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1, // Caja Principal BOB
                'tipo'             => 'ingreso',
                'categoria'        => 'anticipo_cliente',
                'monto'            => 5000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 5000.00,
                'fecha'            => '2026-03-20',
                'concepto'         => 'Adelanto efectivo cliente 3 - Tramo Cochabamba → Trinidad',
                'codigo_seguimiento'=> null,
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCliente',
                'origen_id'        => 6,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ════════════════════════════════════════════════
            //  EGRESOS — Pagos a proveedores
            // ════════════════════════════════════════════════

            // 7. Adelanto proveedor 1 - Contrato 1 (Banco Unión BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_proveedor',
                'monto'            => 20000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 20000.00,
                'fecha'            => '2026-01-04',
                'concepto'         => 'Adelanto proveedor 1 - Contrato CTR-2026-001',
                'codigo_seguimiento'=> 'TRF-PROV-2026-001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoProveedor',
                'origen_id'        => 1,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 8. Pago parcial proveedor 1 - Contrato 1
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_proveedor',
                'monto'            => 35000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 35000.00,
                'fecha'            => '2026-01-20',
                'concepto'         => 'Pago parcial proveedor 1 - CTR-2026-001 (camiones 1 y 2 completados)',
                'codigo_seguimiento'=> 'TRF-PROV-2026-002',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoProveedor',
                'origen_id'        => 2,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 9. Adelanto proveedor 2 - Contrato 2 internacional (Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_proveedor',
                'monto'            => 5000.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 34800.00,
                'fecha'            => '2026-02-03',
                'concepto'         => 'Adelanto USD proveedor 2 - CTR-2026-002 internacional',
                'codigo_seguimiento'=> 'TRF-PROV-USD-2026-001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoProveedor',
                'origen_id'        => 3,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 10. Pago parcial proveedor 2 - Contrato 2 (Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_proveedor',
                'monto'            => 8000.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 55680.00,
                'fecha'            => '2026-02-25',
                'concepto'         => 'Pago parcial USD proveedor 2 - confirmación envío internacional',
                'codigo_seguimiento'=> 'TRF-PROV-USD-2026-002',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoProveedor',
                'origen_id'        => 4,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 11. Adelanto proveedor 1 - Contrato 3 (Caja Principal BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_proveedor',
                'monto'            => 12000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 12000.00,
                'fecha'            => '2026-03-17',
                'concepto'         => 'Adelanto efectivo proveedor 1 - CTR-2026-003',
                'codigo_seguimiento'=> null,
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoProveedor',
                'origen_id'        => 5,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ════════════════════════════════════════════════
            //  EGRESOS — Pagos a camiones (fletes)
            // ════════════════════════════════════════════════

            // 12. Adelanto camión 1 - ContratoCamion 1 (Banco Unión BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 5000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 5000.00,
                'fecha'            => '2026-01-05',
                'concepto'         => 'Adelanto flete - Camión ABC-1234 (Contrato CTR-2026-001)',
                'codigo_seguimiento'=> 'TRF-2026-0001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 1,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 13. Pago final camión 1 - ContratoCamion 1
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 10000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 10000.00,
                'fecha'            => '2026-01-10',
                'concepto'         => 'Pago final flete - Camión ABC-1234 entregado',
                'codigo_seguimiento'=> 'TRF-2026-0002',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 2,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 14. Adelanto camión 2 - ContratoCamion 2 (Caja BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 6000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 6000.00,
                'fecha'            => '2026-01-10',
                'concepto'         => 'Adelanto efectivo flete - Camión XYZ-5678 (Oruro-Cochabamba)',
                'codigo_seguimiento'=> null,
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 3,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 15. Adelanto camión 3 - ContratoCamion 3 (Banco Unión BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 4000.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 4000.00,
                'fecha'            => '2026-01-15',
                'concepto'         => 'Adelanto flete - Camión QRS-9012 CHOQUE (Potosí-Cochabamba)',
                'codigo_seguimiento'=> 'TRF-2026-0003',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 4,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 16. Adelanto camión 1 - ContratoCamion 4 internacional (Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 1000.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 6960.00,
                'fecha'            => '2026-02-05',
                'concepto'         => 'Adelanto USD flete internacional - Camión ABC-1234 (Santa Cruz → São Paulo)',
                'codigo_seguimiento'=> 'TRF-INT-2026-0001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 5,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 17. Adelanto camión 2 - ContratoCamion 5 internacional (Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 1200.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 8352.00,
                'fecha'            => '2026-02-10',
                'concepto'         => 'Adelanto USD flete - Camión XYZ-5678 CHOQUE (La Paz → Buenos Aires)',
                'codigo_seguimiento'=> 'QR-INT-2026-0001',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 6,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 18. Flete parcial camión 2 - ContratoCamion 5 (Bisa USD)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 3,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 1000.00,
                'moneda'           => 'USD',
                'tipo_cambio'      => 6.9600,
                'monto_bolivianos' => 6960.00,
                'fecha'            => '2026-02-20',
                'concepto'         => 'Flete parcial USD - Camión XYZ-5678 transbordado en frontera',
                'codigo_seguimiento'=> 'TRF-INT-2026-0002',
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 7,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 19. Adelanto camión 3 - ContratoCamion 6 (Caja BOB)
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_camion',
                'monto'            => 3500.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 3500.00,
                'fecha'            => '2026-03-18',
                'concepto'         => 'Adelanto efectivo flete - Camión QRS-9012 CHOQUE (Cochabamba → Trinidad)',
                'codigo_seguimiento'=> null,
                'observaciones'    => null,
                'origen_type'      => 'App\Models\PagoCamion',
                'origen_id'        => 8,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ════════════════════════════════════════════════
            //  EGRESOS — Sueldos empleados
            // ════════════════════════════════════════════════

            // 20. Sueldo Ana Gutierrez - Enero
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2, // Banco Unión BOB
                'tipo'             => 'egreso',
                'categoria'        => 'pago_sueldo',
                'monto'            => 4500.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 4500.00,
                'fecha'            => '2026-01-31',
                'concepto'         => 'Sueldo enero 2026 - Ana Gutierrez (Administradora)',
                'codigo_seguimiento'=> 'SUELDO-2026-01-001',
                'observaciones'    => null,
                'origen_type'      => null,
                'origen_id'        => null,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 21. Sueldo Carlos Mendoza - Enero
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 2,
                'tipo'             => 'egreso',
                'categoria'        => 'pago_sueldo',
                'monto'            => 5200.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 5200.00,
                'fecha'            => '2026-01-31',
                'concepto'         => 'Sueldo enero 2026 - Carlos Mendoza (Contador)',
                'codigo_seguimiento'=> 'SUELDO-2026-01-002',
                'observaciones'    => null,
                'origen_type'      => null,
                'origen_id'        => null,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 22. Sueldo Rosa Ticona - Enero
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1, // Caja BOB
                'tipo'             => 'egreso',
                'categoria'        => 'pago_sueldo',
                'monto'            => 3800.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 3800.00,
                'fecha'            => '2026-01-31',
                'concepto'         => 'Sueldo enero 2026 - Rosa Ticona (Asistente Logística)',
                'codigo_seguimiento'=> 'SUELDO-2026-01-003',
                'observaciones'    => null,
                'origen_type'      => null,
                'origen_id'        => null,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ════════════════════════════════════════════════
            //  EGRESOS — Gastos varios
            // ════════════════════════════════════════════════

            // 23. Gasto extra - combustible y peajes
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1, // Caja BOB
                'tipo'             => 'egreso',
                'categoria'        => 'gasto_extra',
                'monto'            => 2800.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 2800.00,
                'fecha'            => '2026-01-08',
                'concepto'         => 'Gasto combustible y peajes - viajes enero 2026',
                'codigo_seguimiento'=> null,
                'observaciones'    => 'Reposición de caja chica por gastos de operación',
                'origen_type'      => null,
                'origen_id'        => null,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // 24. Gasto administrativo - servicios oficina
            [
                'uuid'             => Str::uuid(),
                'lote_pago_id'     => null,
                'cuenta_empresa_id'=> 1,
                'tipo'             => 'egreso',
                'categoria'        => 'gasto_extra',
                'monto'            => 950.00,
                'moneda'           => 'BOB',
                'tipo_cambio'      => 1.0000,
                'monto_bolivianos' => 950.00,
                'fecha'            => '2026-02-01',
                'concepto'         => 'Servicios de oficina - internet, teléfono, alquiler febrero',
                'codigo_seguimiento'=> null,
                'observaciones'    => null,
                'origen_type'      => null,
                'origen_id'        => null,
                'created_by'       => 1,
                'updated_by'       => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
        ]);
    }
}
